/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regla.falsa;

import java.text.DecimalFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Regla_falsa extends javax.swing.JFrame {

    public Regla_falsa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFondoBlanco = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();
        txtSexta = new javax.swing.JTextField();
        txtQuinta = new javax.swing.JTextField();
        txtCuarta = new javax.swing.JTextField();
        txtTercera = new javax.swing.JTextField();
        txtSegunda = new javax.swing.JTextField();
        txtPrimera = new javax.swing.JTextField();
        lbPrimera = new javax.swing.JLabel();
        lbSexta = new javax.swing.JLabel();
        lbQuinta = new javax.swing.JLabel();
        lbCuarta = new javax.swing.JLabel();
        lbTercera = new javax.swing.JLabel();
        lbSegunda = new javax.swing.JLabel();
        lbIntervalo = new javax.swing.JLabel();
        lbPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        lbDecimales = new javax.swing.JLabel();
        cbDecimales = new javax.swing.JComboBox();
        txtA = new javax.swing.JTextField();
        lbA = new javax.swing.JLabel();
        lbB = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        txtConstante = new javax.swing.JTextField();
        lbConstante = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pFondoAzul = new javax.swing.JPanel();
        pFondoAmarillo = new javax.swing.JPanel();
        lTitulo1 = new javax.swing.JLabel();
        lTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        pFondoBlanco.setForeground(new java.awt.Color(204, 0, 204));
        pFondoBlanco.setLayout(null);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pFondoBlanco.add(jButton1);
        jButton1.setBounds(530, 260, 73, 30);

        lbTexto.setText("Llena los campos que necesites para operar(Si no necesitas alguno llenalo con un cero):");
        pFondoBlanco.add(lbTexto);
        lbTexto.setBounds(20, 10, 630, 16);

        txtSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSextaActionPerformed(evt);
            }
        });
        txtSexta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSextaKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtSexta);
        txtSexta.setBounds(20, 40, 40, 30);

        txtQuinta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuintaKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtQuinta);
        txtQuinta.setBounds(110, 40, 40, 30);

        txtCuarta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuartaKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtCuarta);
        txtCuarta.setBounds(200, 40, 40, 30);

        txtTercera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTerceraKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtTercera);
        txtTercera.setBounds(290, 40, 40, 30);

        txtSegunda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundaKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtSegunda);
        txtSegunda.setBounds(380, 40, 40, 30);

        txtPrimera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrimeraKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtPrimera);
        txtPrimera.setBounds(470, 40, 40, 30);

        lbPrimera.setText("x");
        pFondoBlanco.add(lbPrimera);
        lbPrimera.setBounds(520, 50, 34, 16);

        lbSexta.setText("x^6");
        pFondoBlanco.add(lbSexta);
        lbSexta.setBounds(70, 50, 21, 16);

        lbQuinta.setText("x^5");
        pFondoBlanco.add(lbQuinta);
        lbQuinta.setBounds(160, 50, 34, 16);

        lbCuarta.setText("x^4");
        pFondoBlanco.add(lbCuarta);
        lbCuarta.setBounds(250, 50, 34, 16);

        lbTercera.setText("x^3");
        pFondoBlanco.add(lbTercera);
        lbTercera.setBounds(340, 50, 34, 16);

        lbSegunda.setText("x^2");
        pFondoBlanco.add(lbSegunda);
        lbSegunda.setBounds(430, 50, 34, 16);

        lbIntervalo.setText("Intervalo");
        pFondoBlanco.add(lbIntervalo);
        lbIntervalo.setBounds(50, 100, 180, 16);

        lbPorcentaje.setText("Porcentaje de error:");
        pFondoBlanco.add(lbPorcentaje);
        lbPorcentaje.setBounds(10, 180, 170, 16);

        txtPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeActionPerformed(evt);
            }
        });
        txtPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtPorcentaje);
        txtPorcentaje.setBounds(140, 170, 70, 30);

        lbDecimales.setText("Numero de decimales:");
        pFondoBlanco.add(lbDecimales);
        lbDecimales.setBounds(50, 220, 160, 16);

        cbDecimales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cbDecimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDecimalesActionPerformed(evt);
            }
        });
        pFondoBlanco.add(cbDecimales);
        cbDecimales.setBounds(50, 250, 50, 30);

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtA);
        txtA.setBounds(40, 120, 40, 30);

        lbA.setText("A");
        pFondoBlanco.add(lbA);
        lbA.setBounds(20, 130, 20, 16);

        lbB.setText("B");
        pFondoBlanco.add(lbB);
        lbB.setBounds(90, 130, 34, 16);

        txtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtB);
        txtB.setBounds(110, 120, 40, 30);

        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConstanteKeyTyped(evt);
            }
        });
        pFondoBlanco.add(txtConstante);
        txtConstante.setBounds(550, 40, 40, 30);

        lbConstante.setText("C");
        pFondoBlanco.add(lbConstante);
        lbConstante.setBounds(600, 50, 30, 16);
        pFondoBlanco.add(jSeparator2);
        jSeparator2.setBounds(0, 90, 660, 10);

        getContentPane().add(pFondoBlanco);
        pFondoBlanco.setBounds(0, 60, 660, 350);

        pFondoAzul.setBackground(new java.awt.Color(0, 0, 153));

        pFondoAmarillo.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout pFondoAmarilloLayout = new javax.swing.GroupLayout(pFondoAmarillo);
        pFondoAmarillo.setLayout(pFondoAmarilloLayout);
        pFondoAmarilloLayout.setHorizontalGroup(
            pFondoAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pFondoAmarilloLayout.setVerticalGroup(
            pFondoAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        lTitulo1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo1.setText("REGLA FALSA");

        javax.swing.GroupLayout pFondoAzulLayout = new javax.swing.GroupLayout(pFondoAzul);
        pFondoAzul.setLayout(pFondoAzulLayout);
        pFondoAzulLayout.setHorizontalGroup(
            pFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFondoAmarillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pFondoAzulLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        pFondoAzulLayout.setVerticalGroup(
            pFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFondoAzulLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pFondoAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(pFondoAzul);
        pFondoAzul.setBounds(0, 0, 660, 100);

        lTitulo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lTitulo.setText("TEOREMA DE ROLLE");
        getContentPane().add(lTitulo);
        lTitulo.setBounds(10, 11, 480, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     float dSexta;
    float dQuinta = 0;
    float dCuarta = 0;
    float dTercera = 0;
    float dSegunda = 0;
    float dPrimera = 0;
    float dIntervaloA = 0;
    float dIntervaloB = 0;
    int iDecimales = 0;
    float dConstate = 0;
    float dFuncionA = 0;
    float dFuncionB = 0;
    float dFuncionC = 0;
    float dFuncionD = 0;
    float dFunciones = 0;
    float auxfuncionA = 0;
    float auxfuncionB = 0;
    float xr;
    float xr1;
    float rError;
    float rateError;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            dSexta = Float.parseFloat(txtSexta.getText().trim());
            dQuinta = Float.parseFloat(txtQuinta.getText().trim());
            dCuarta = Float.parseFloat(txtCuarta.getText().trim());
            dTercera = Float.parseFloat(txtTercera.getText().trim());
            dSegunda = Float.parseFloat(txtSegunda.getText().trim());
            dPrimera = Float.parseFloat(txtPrimera.getText().trim());
            dConstate = Float.parseFloat(txtConstante.getText().trim());

            dIntervaloA = Float.parseFloat(txtA.getText().trim());
            dIntervaloB = Float.parseFloat(txtB.getText().trim());
            iDecimales = Integer.parseInt(cbDecimales.getSelectedItem().toString());

            rateError = Float.parseFloat(txtPorcentaje.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hay un error en tus datos o hay un campo vacio");
        }
        //funciones para los intervalos

        
            System.out.println("intervalo A: " + dIntervaloA);//2
            System.out.println("intervalo B: " + dIntervaloB);//8
            dFuncionA =  (float) ((dSexta * (Math.pow(dIntervaloA, 6))) + (dQuinta * (Math.pow(dIntervaloA, 5))) + (dCuarta * (Math.pow(dIntervaloA, 4))) + (dTercera * (Math.pow(dIntervaloA, 3))) + (dSegunda * (Math.pow(dIntervaloA, 2))) + (dPrimera * dIntervaloA) + (dConstate));
            System.out.println("f(a) = " + dFuncionA);//-2
            dFuncionB = (float) ((dSexta * (Math.pow(dIntervaloB, 6))) + (dQuinta * (Math.pow(dIntervaloB, 5))) + (dCuarta * (Math.pow(dIntervaloB, 4))) + (dTercera * (Math.pow(dIntervaloB, 3))) + (dSegunda * (Math.pow(dIntervaloB, 2))) + (dPrimera * dIntervaloB) + (dConstate));
            System.out.println("f(b) = " + dFuncionB);//28

            if (dFuncionA * dFuncionB < 0) {
                xr = ((dFuncionA * dIntervaloB) - (dFuncionB * dIntervaloA)) / (dFuncionA - dFuncionB);
                System.out.println("xr = " +xr);

                auxfuncionA = xr;  //1.67
                dFuncionC = (float) ((dSexta * Math.pow(auxfuncionA, 6)) + (dQuinta * Math.pow(auxfuncionA, 5)) + (dCuarta * Math.pow(auxfuncionA, 4)) + (dTercera * Math.pow(auxfuncionA, 3))
                        + (dSegunda * Math.pow(auxfuncionA, 2)) + (dPrimera * auxfuncionA) + dConstate);  //-0.5786

                auxfuncionB = dIntervaloB; //2
                dFuncionD = (float) ((dSexta * Math.pow(auxfuncionB, 6)) + (dQuinta * Math.pow(auxfuncionB, 5)) + (dCuarta * Math.pow(auxfuncionB, 4)) + (dTercera * Math.pow(auxfuncionB, 3))
                        + (dSegunda * Math.pow(auxfuncionB, 2)) + (dPrimera * auxfuncionB) + dConstate);  //5 

                do {

                    xr1 = dIntervaloB - ((dFuncionD * xr) - (dFuncionD * dIntervaloB)) / (dFuncionC - dFuncionD);
                    System.out.println("X = " + xr1); //1.2531

                    rError = Math.abs((xr1 - xr) / xr1) * 100;
                    System.out.println("Error relativo: " + rError);

                    xr = xr1; //1.2531
                    dFuncionC = (float) ((dSexta * Math.pow(xr, 6)) + (dQuinta * Math.pow(xr, 5)) + (dCuarta * Math.pow(xr, 4)) + (dTercera * Math.pow(xr, 3))
                            + (dSegunda * Math.pow(xr, 2)) + (dPrimera * xr) + dConstate); //-0.2854
                    System.out.println();

                } while (rateError < rError);

            } else if (dFuncionA * dFuncionB == 0) {
                xr = ((dFuncionA * dIntervaloB) - (dFuncionB * dIntervaloB)) / (dFuncionA - dFuncionB);
                JOptionPane.showMessageDialog(null, "La raiz es:" + xr);

            } else {
                JOptionPane.showMessageDialog(null, "Ingresa nuevos intervalos");
            }
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSextaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSextaActionPerformed

    private void txtSextaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSextaKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtSextaKeyTyped

    private void txtQuintaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuintaKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtQuintaKeyTyped

    private void txtCuartaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuartaKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtCuartaKeyTyped

    private void txtTerceraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTerceraKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtTerceraKeyTyped

    private void txtSegundaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundaKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundaKeyTyped

    private void txtPrimeraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimeraKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimeraKeyTyped

    private void txtPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeActionPerformed

    private void txtPorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeKeyTyped

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed

    }//GEN-LAST:event_txtAActionPerformed

    private void txtAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtAKeyTyped

    private void txtBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBKeyTyped
        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_txtBKeyTyped

    private void txtConstanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyTyped

        char numero = evt.getKeyChar();
        if (Character.isLetter(numero) || Character.isSpaceChar(numero)) {
            evt.consume();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtConstanteKeyTyped

    private void cbDecimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDecimalesActionPerformed

        if(cbDecimales.getSelectedItem().equals(1)){
            DecimalFormat formato = new DecimalFormat("#.#");
           System.out.println(formato.format(rError));
       }
        
    }//GEN-LAST:event_cbDecimalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regla_falsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regla_falsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regla_falsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regla_falsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regla_falsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDecimales;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lTitulo1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbConstante;
    private javax.swing.JLabel lbCuarta;
    private javax.swing.JLabel lbDecimales;
    private javax.swing.JLabel lbIntervalo;
    private javax.swing.JLabel lbPorcentaje;
    private javax.swing.JLabel lbPrimera;
    private javax.swing.JLabel lbQuinta;
    private javax.swing.JLabel lbSegunda;
    private javax.swing.JLabel lbSexta;
    private javax.swing.JLabel lbTercera;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JPanel pFondoAmarillo;
    private javax.swing.JPanel pFondoAzul;
    private javax.swing.JPanel pFondoBlanco;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtCuarta;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtPrimera;
    private javax.swing.JTextField txtQuinta;
    private javax.swing.JTextField txtSegunda;
    private javax.swing.JTextField txtSexta;
    private javax.swing.JTextField txtTercera;
    // End of variables declaration//GEN-END:variables
}
